FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
COPY apps/api/package*.json ./apps/api/
RUN npm ci --ignore-scripts
COPY apps/api ./apps/api
ENV NODE_OPTIONS="--max-old-space-size=4096"
RUN cd apps/api && npx nest build

FROM node:20-alpine
WORKDIR /app
COPY --from=builder /app/apps/api/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/apps/api/package*.json ./
EXPOSE 3000
CMD ["node", "dist/src/main.js"]
