[build]
  base    = "apps/web-admin"
  command = "npm install && npm run build"
  publish = "apps/web-admin/.next"

[build.environment]
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-nextjs"
